apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./secrets/license.yaml
  - ./secrets/certificates.yaml
  - ./ingress.yaml

helmCharts:
  - repo: https://charts.konghq.com
    name: kong
    releaseName: kong
    namespace: kong
    includeCRDs: false
    valuesFile: values.yaml
