ingressController:
  installCRDs: true
  ingressClassName: "kong"
  watchNamespaces: ""
  env:
    # admin_listen: "0.0.0.0:8001"
    admin_gui_url: "http://manager.minikube"
    admin_api_uri: "http://admin.minikube"
  rbac:
    create: true

# Mount the secret created earlier
secretVolumes:
  - kong-cluster-cert

env:
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  database: postgres
  pg_database: kong
  pg_user: kong
  pg_password: demo123
  pg_host: kong-postgresql.kong.svc.cluster.local
  pg_ssl: "off"
  password: admin
  admin_gui_url: http://manager.minikube
  admin_gui_api_url: http://admin.minikube
  # Change the secret and set cookie_secure to true if using a HTTPS endpoint
  admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":false}'
  # cluster_listen: "0.0.0.0:8005"
  # cluster_control_plane: "kong-cp-gateway-admin.kong.svc:8001" # Ensure this is correctly pointing to the Admin API service

# The control plane serves the Admin API
admin:
  enabled: true
  http:
    enabled: true
    servicePort: 80
    nodePort: 32000
  tls:
    enabled: false

manager:
  enabled: true
  http:
    enabled: true
    servicePort: 80
    nodePort: 32001
  tls:
    enabled: false

postgresql:
  enabled: true
  auth:
    database: kong
    password: demo123
    username: kong
# These roles will be served by different Helm releases
proxy:
  enabled: true
  type: LoadBalancer
  http:
    servicePort: 80
    nodePort: 30000
  tls:
    servicePort: 443
    nodePort: 30001
